kernel:
  image: linuxkit/kernel:4.19.99
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:a4fcf333298f644dfac6adf680b83140927aa85e
  - linuxkit/runc:69b4a35eaa22eba4990ee52cccc8f48f6c08ed03
  - linuxkit/containerd:09553963ed9da626c25cf8acdf6d62ec37645412
  - linuxkit/ca-certificates:v0.7
  - linuxkit/memlogd:v0.7
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.7
  - name: sysfs
    image: linuxkit/sysfs:v0.7
  - name: rngd1
    image: linuxkit/rngd:v0.7
    command: ["/sbin/rngd", "-1"]
  - name: dhcpcd1
    image: linuxkit/dhcpcd:v0.7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:v0.7
  - name: logwrite
    image: linuxkit/logwrite:v0.7
  - name: kmsg
    image: linuxkit/kmsg:v0.7
  - name: ntpd
    image: linuxkit/openntpd:v0.7
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
  - name: getty
    image: linuxkit/getty:v0.7
    env:
      - INSECURE=true
  - name: agent
    image: rbelgrave/agent:dev
trust:
  org:
  - linuxkit