kernel:
  image: linuxkit/kernel:4.19.99
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:7195dc244cd92af01fd0895fd204249a6114c5e2
  - linuxkit/runc:f79954950022fea76b8b6f10de58cb48e4fb3878
  - linuxkit/containerd:6ef473a228db6f6ee163f9b9a051102a1552a4ef
  - linuxkit/ca-certificates:abfc6701b9ca17e34ac9439ce5946a247e720ff5
  - linuxkit/memlogd:v0.7
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.7
  - name: sysfs
    image: linuxkit/sysfs:v0.7
  - name: rngd1
    image: linuxkit/rngd:v0.7
    command: ["/sbin/rngd", "-1"]
  - name: dhcpcd1
    image: linuxkit/dhcpcd:v0.7
    # Only enable DHCP for eth0
    # This prevents multiple nics on the same network from requesting IPs
    # If multiple nics on the same network get IPs the 2nd IP doesn't end up working correctly
    # Multiple nics can be on the same network if they will eventually be bonded
    # I would like to find a better fix eventually
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1", "eth0"]
services:
  - name: rngd
    image: linuxkit/rngd:v0.7
  - name: logwrite
    image: linuxkit/logwrite:v0.7
  - name: kmsg
    image: linuxkit/kmsg:v0.7
  - name: ntpd
    image: linuxkit/openntpd:v0.7
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "eth0"]
  - name: acpid
    image: linuxkit/acpid:v0.7
  - name: getty
    image: linuxkit/getty:v0.7
    env:
      - INSECURE=true
  - name: sshd
    image: linuxkit/sshd:v0.7
  - name: agent
    image: docker.pkg.github.com/rmb938/kube-baremetal/agent:dev
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit
