
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-baremetal-com-rmb938-v1alpha1-baremetaldiscovery
  failurePolicy: Fail
  name: mbaremetaldiscovery.kb.io
  rules:
  - apiGroups:
    - baremetal.com.rmb938
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - baremetaldiscoveries
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-baremetal-com-rmb938-v1alpha1-baremetalendpoint
  failurePolicy: Fail
  name: mbaremetalendpoint.kb.io
  rules:
  - apiGroups:
    - baremetal.com.rmb938
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - baremetalendpoints
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-baremetal-com-rmb938-v1alpha1-baremetalhardware
  failurePolicy: Fail
  name: mbaremetalhardware.kb.io
  rules:
  - apiGroups:
    - baremetal.com.rmb938
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - baremetalhardwares
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-baremetal-com-rmb938-v1alpha1-baremetalinstance
  failurePolicy: Fail
  name: mbaremetalinstance.kb.io
  rules:
  - apiGroups:
    - baremetal.com.rmb938
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - baremetalinstances

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-baremetal-com-rmb938-v1alpha1-baremetaldiscovery
  failurePolicy: Fail
  name: vbaremetaldiscovery.kb.io
  rules:
  - apiGroups:
    - baremetal.com.rmb938
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - baremetaldiscoveries
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-baremetal-com-rmb938-v1alpha1-baremetalendpoint
  failurePolicy: Fail
  name: vbaremetalendpoint.kb.io
  rules:
  - apiGroups:
    - baremetal.com.rmb938
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - baremetalendpoints
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-baremetal-com-rmb938-v1alpha1-baremetalhardware
  failurePolicy: Fail
  name: vbaremetalhardware.kb.io
  rules:
  - apiGroups:
    - baremetal.com.rmb938
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - baremetalhardwares
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-baremetal-com-rmb938-v1alpha1-baremetalinstance
  failurePolicy: Fail
  name: vbaremetalinstance.kb.io
  rules:
  - apiGroups:
    - baremetal.com.rmb938
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - baremetalinstances
