# permissions to do viewer baremetalinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baremetalinstance-viewer-role
rules:
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetalinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetalinstances/status
  verbs:
  - get
