# permissions to do viewer baremetalendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baremetalendpoint-viewer-role
rules:
  - apiGroups:
      - baremetal.com.rmb938
    resources:
      - baremetalendpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - baremetal.com.rmb938
    resources:
      - baremetalendpoints/status
    verbs:
      - get
