
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetaldiscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetaldiscoveries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetalhardwares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetalhardwares/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetalinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baremetal.com.rmb938
  resources:
  - baremetalinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - baremetal.rmb938.com
  resources:
  - baremetalendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baremetal.rmb938.com
  resources:
  - baremetalendpoints/status
  verbs:
  - get
  - patch
  - update
