apiVersion: baremetal.com.rmb938/v1alpha1
kind: BareMetalHardware
metadata:
  name: baremetalhardware-sample
spec:
  systemUUID: f4fe74ae-c4e0-4eed-96b2-fc4692e7b396
  imageDrive: vda
  nics:
    - name: eth0
      primary: true
      networkRef:
        name: baremetalnetwork-sample
        kind: BareMetalNetwork
        group: baremetal.com.rmb938

