apiVersion: baremetal.com.rmb938/v1alpha1
kind: BareMetalHardware
metadata:
  name: baremetalhardware-sample
spec:
  systemUUID: 00000000-0000-0000-0000-f3ee00f0f3ee
  imageDrive: nvme0n1
  nics:
    - name: eth0
      primary: true
      networkRef:
        name: ""
        kind: ""
        group: ""

