apiVersion: baremetal.com.rmb938/v1alpha1
kind: BareMetalHardware
metadata:
  name: baremetalhardware-sample
spec:
  systemUUID: 00000000-0000-0000-0000-f3ee00f0f3ee
  imageDrive: nvme0n1
  nics:
    - name: bond0
      primary: true
      bond:
        interfaces:
          - eth0
          - eth1
        mode: active-backup
      networkRef:
        name: baremetalnetwork-sample
        kind: BareMetalNetwork
        group: baremetal.com.rmb938

