// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalDiscovery) DeepCopyInto(out *BareMetalDiscovery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalDiscovery.
func (in *BareMetalDiscovery) DeepCopy() *BareMetalDiscovery {
	if in == nil {
		return nil
	}
	out := new(BareMetalDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BareMetalDiscovery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalDiscoveryHardware) DeepCopyInto(out *BareMetalDiscoveryHardware) {
	*out = *in
	in.CPU.DeepCopyInto(&out.CPU)
	out.Ram = in.Ram.DeepCopy()
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = make([]BareMetalDiscoveryHardwareStorage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NICS != nil {
		in, out := &in.NICS, &out.NICS
		*out = make([]BareMetalDiscoveryHardwareNIC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalDiscoveryHardware.
func (in *BareMetalDiscoveryHardware) DeepCopy() *BareMetalDiscoveryHardware {
	if in == nil {
		return nil
	}
	out := new(BareMetalDiscoveryHardware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalDiscoveryHardwareCPU) DeepCopyInto(out *BareMetalDiscoveryHardwareCPU) {
	*out = *in
	out.CPUS = in.CPUS.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalDiscoveryHardwareCPU.
func (in *BareMetalDiscoveryHardwareCPU) DeepCopy() *BareMetalDiscoveryHardwareCPU {
	if in == nil {
		return nil
	}
	out := new(BareMetalDiscoveryHardwareCPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalDiscoveryHardwareNIC) DeepCopyInto(out *BareMetalDiscoveryHardwareNIC) {
	*out = *in
	out.Speed = in.Speed.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalDiscoveryHardwareNIC.
func (in *BareMetalDiscoveryHardwareNIC) DeepCopy() *BareMetalDiscoveryHardwareNIC {
	if in == nil {
		return nil
	}
	out := new(BareMetalDiscoveryHardwareNIC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalDiscoveryHardwareStorage) DeepCopyInto(out *BareMetalDiscoveryHardwareStorage) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalDiscoveryHardwareStorage.
func (in *BareMetalDiscoveryHardwareStorage) DeepCopy() *BareMetalDiscoveryHardwareStorage {
	if in == nil {
		return nil
	}
	out := new(BareMetalDiscoveryHardwareStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalDiscoveryList) DeepCopyInto(out *BareMetalDiscoveryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BareMetalDiscovery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalDiscoveryList.
func (in *BareMetalDiscoveryList) DeepCopy() *BareMetalDiscoveryList {
	if in == nil {
		return nil
	}
	out := new(BareMetalDiscoveryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BareMetalDiscoveryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalDiscoverySpec) DeepCopyInto(out *BareMetalDiscoverySpec) {
	*out = *in
	if in.Hardware != nil {
		in, out := &in.Hardware, &out.Hardware
		*out = new(BareMetalDiscoveryHardware)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalDiscoverySpec.
func (in *BareMetalDiscoverySpec) DeepCopy() *BareMetalDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(BareMetalDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalDiscoveryStatus) DeepCopyInto(out *BareMetalDiscoveryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalDiscoveryStatus.
func (in *BareMetalDiscoveryStatus) DeepCopy() *BareMetalDiscoveryStatus {
	if in == nil {
		return nil
	}
	out := new(BareMetalDiscoveryStatus)
	in.DeepCopyInto(out)
	return out
}
