- hosts: localhost
  connection: local
  name: SETUP DEV WITH LIBVIRT
  vars:
    network_bridge: kbm0
  tasks:
    - name: DOWNLOAD IPXE
      become: yes
      get_url:
        url: http://boot.ipxe.org/ipxe.efi
        checksum: sha256:2c8d824eecabddafacbbf02043f0d0e04ba9e14c30f2f9493e00782206721c68
        dest: "/usr/share/ipxe/ipxe.efi"
        mode: 0644

    - name: SETUP NETWORK
      become: yes
      virt_net:
        command: define
        name: kube-baremetal
        xml: '{{ lookup("template", "network.xml") }}'

    - name: ACTIVATE NETWORK
      become: yes
      virt_net:
        state: active
        name: kube-baremetal

    - name: ALLOW VM TO ATTACH TO NETWORK
      become: yes
      lineinfile:
        path: /etc/qemu/bridge.conf
        line: "allow {{ network_bridge }}"

    - name: CREATE VM DISK
      shell: "qemu-img create -f qcow2 -o size=20G {{ playbook_dir }}/../vms/kube-baremetal-0.qcow2"
      args:
        creates: "{{ playbook_dir }}/../vms/kube-baremetal-0.qcow2"

    - name: CREATE VM
      virt:
        uri: "qemu:///session"
        command: define
        xml: "{{ lookup('template', 'vm.xml') }}"
